# -*- coding: utf-8 -*-

capitals = {
    'Afghanistan': 'Kabul',
    'Albania': 'Tirana',
    'Algeria': 'Algiers',
    'Andorra': 'Andorra la Vella',
    'Angola': 'Luanda',
    'Antigua and Barbuda': 'St.Johns',
    'Argentina': 'Buenos Aires',
    'Armenia': 'Yerevan',
    'Australia': 'Canberra',
    'Austria': 'Vienna',
    'Azerbaijan': 'Baku',
    'Bahamas': 'Nassau',
    'Bahrain': 'Manama',
    'Bangladesh': 'Dhaka',
    'Barbados': 'Bridgetown',
    'Belarus': 'Minsk',
    'Belgium': 'Brussels',
    'Belize': 'Belmopan',
    'Benin': 'Porto Novo',
    'Bhutan': 'Thimphu',
    'Bolivia': 'Sucre',
    'Bolivia': 'La Paz',
    'Bosnia and Herzegovina': 'Sarajevo',
    'Botswana': 'Gaborone',
    'Brazil': 'Brasilia',
    'Brunei': 'Bandar Seri Begawan',
    'Bulgaria': 'Sofia',
    'Burkina Faso': 'Ouagadougou',
    'Burundi': 'Bujumbura',
    'Cambodia': 'Phnom Penh',
    'Cameroon': 'Yaounde',
    'Canada': 'Ottawa',
    'Cape Verde': 'Praia',
    'Central African Republic': 'Bangui',
    'Chad': 'NDjamena',
    'Chile': 'Santiago',
    'China': 'Beijing',
    'Colombia': 'Bogota',
    'Comoros': 'Moroni',
    'Congo': 'Brazzaville',
    'Democratic Republic of the Congo': 'Kinshasa',
    'Costa Rica': 'San Jose',
    'Cote d\'Ivoire': 'Yamoussoukro',
    'Croatia': 'Zagreb',
    'Cuba': 'Havana',
    'Cyprus': 'Nicosia',
    'Czech Republic': 'Prague',
    'Denmark': 'Copenhagen',
    'Djibouti': 'Djibouti',
    'Dominica': 'Roseau',
    'Dominican Republic': 'Santo Domingo',
    'East Timor': 'Dili',
    'Ecuador': 'Quito',
    'Egypt': 'Cairo',
    'El Salvador': 'San Salvador',
    'Equatorial Guinea': 'Malabo',
    'Eritrea': 'Asmara',
    'Estonia': 'Tallinn',
    'Ethiopia': 'Addis Ababa',
    'Fiji': 'Suva',
    'Finland': 'Helsinki',
    'France': 'Paris',
    'Gabon': 'Libreville',
    'Gambia': 'Banjul',
    'Georgia': 'Tbilisi',
    'Germany': 'Berlin',
    'Ghana': 'Accra',
    'Greece': 'Athens',
    'Grenada': 'St.Georges',
    'Guatemala': 'Guatemala City',
    'Guinea': 'Conakry',
    'Guinea-Bissau': 'Bissau',
    'Guyana': 'Georgetown',
    'Haiti': 'Port au Prince',
    'Vatican City': 'Vatican City',
    'Honduras': 'Tegucigalpa',
    'Hungary': 'Budapest',
    'Iceland': 'Reykjavik',
    'India': 'New Delhi',
    'Indonesia': 'Jakarta',
    'Iran': 'Tehran',
    'Iraq': 'Baghdad',
    'Ireland': 'Dublin',
    'Israel': 'Jerusalem',
    'Israel': 'Tel Aviv',
    'Italy': 'Rome',
    'Jamaica': 'Kingston',
    'Japan': 'Tokyo',
    'Jordan': 'Amman',
    'Kazakhstan': 'Astana',
    'Kenya': 'Nairobi',
    'Kiribati': 'Tarawa',
    'Kiribati': 'Tarawa Atoll',
    'North Korea': 'Pyongyang',
    'South Korea': 'Seoul',
    'Kuwait': 'Kuwait City',
    'Kyrgyzstan': 'Bishkek',
    'Laos': 'Vientiane',
    'Latvia': 'Riga',
    'Lebanon': 'Beirut',
    'Lesotho': 'Maseru',
    'Liberia': 'Monrovia',
    'Libya': 'Tripoli',
    'Liechtenstein': 'Vaduz',
    'Lithuania': 'Vilnius',
    'Luxembourg': 'Luxembourg',
    'Macedonia': 'Skopje',
    'Madagascar': 'Antananarivo',
    'Malawi': 'Lilongwe',
    'Malaysia': 'Kuala Lumpur',
    'Maldives': 'Male',
    'Mali': 'Bamako',
    'Malta': 'Valletta',
    'Marshall Islands': 'Majuro',
    'Mauritania': 'Nouakchott',
    'Mauritius': 'Port Louis',
    'Mexico': 'Mexico City',
    'Federated States of Micronesia': 'Palikir',
    'Moldova': 'Chisinau',
    'Monaco': 'Monaco',
    'Mongolia': 'Ulaanbaatar',
    'Montenegro': 'Podgorica',
    'Morocco': 'Rabat',
    'Mozambique': 'Maputo',
    'Myanmar': 'Naypyidaw',
    'Namibia': 'Windhoek',
    'Nauru': 'Yaren District',
    'Nepal': 'Kathmandu',
    'Netherlands': 'Amsterdam',
    'New Zealand': 'Wellington',
    'Nicaragua': 'Managua',
    'Niger': 'Niamey',
    'Nigeria': 'Abuja',
    'Norway': 'Oslo',
    'Oman': 'Muscat',
    'Pakistan': 'Islamabad',
    'Palau': 'Melekeok',
    'Panama': 'Panama City',
    'Papua New Guinea': 'Port Moresby',
    'Paraguay': 'Asuncion',
    'Peru': 'Lima',
    'Philippines': 'Manila',
    'Poland': 'Warsaw',
    'Portugal': 'Lisbon',
    'Qatar': 'Doha',
    'Romania': 'Bucharest',
    'Russia': 'Moscow',
    'Rwanda': 'Kigali',
    'Saint Kitts and Nevis': 'Basseterre',
    'SaintLucia': 'Castries',
    'Saint Vincent and the Grenadines': 'Kingstown',
    'Samoa': 'Apia',
    'San Marino': 'San Marino',
    'Sao Tome and Principe': 'Sao Tome',
    'Saudi Arabia': 'Riyadh',
    'Scotland': 'Edinburgh',
    'Senegal': 'Dakar',
    'Serbia': 'Belgrade',
    'Seychelles': 'Victoria',
    'Sierra Leone': 'Freetown',
    'Singapore': 'Singapore',
    'Slovakia': 'Bratislava',
    'Slovenia': 'Ljubljana',
    'Solomon Islands': 'Honiara',
    'Somalia': 'Mogadishu',
    'South Africa': 'Pretoria',
    'Spain': 'Madrid',
    'Sri Lanka': 'Colombo',
    'Sudan': 'Khartoum',
    'Suriname': 'Paramaribo',
    'Swaziland': 'Mbabane',
    'Swaziland': 'Mbabana',
    'Sweden': 'Stockholm',
    'Switzerland': 'Bern',
    'Syria': 'Damascus',
    'Taiwan': 'Taipei',
    'Tajikistan': 'Dushanbe',
    'Tanzania': 'Dodoma',
    'Thailand': 'Bangkok',
    'Togo': 'Lome',
    'Tonga': 'Nukualofa',
    'Trinidad and Tobago': 'Port of Spain',
    'Tunisia': 'Tunis',
    'Turkey': 'Ankara',
    'Turkmenistan': 'Ashgabat',
    'Tuvalu': 'Funafuti',
    'Uganda': 'Kampala',
    'Ukraine': 'Kiev',
    'United Arab Emirates': 'Abu Dhabi',
    'England': 'London',
    'United States': 'Washington D.C.',
    'Uruguay': 'Montevideo',
    'Uzbekistan': 'Tashkent',
    'Vanuatu': 'Port Vila',
    'Venezuela': 'Caracas',
    'Vietnam': 'Hanoi',
    'Wales': 'Cardiff',
    'Yemen': 'Sanaa',
    'Zambia': 'Lusaka',
    'Zimbabwe': 'Harare',
    'American Samoa': 'Pago Pago',
    'Anguilla': 'The Valley',
    'Aruba': 'Oranjestad',
    'Azores': 'Ponta Delgada',
    'Bermuda': 'Hamilton',
    'Canary Islands': 'Las Palmas',
    # 'Ascension Island': 'Georgetown',
    'Cayman Islands': 'George Town',
    'Christmas Island': 'The Settlement',
    'Cocos Islands': 'West Island',
    'Cook Islands': 'Avarua',
    'Falkland Islands': 'Stanley',
    'Faroe Islands': 'Torshavn',
    'French Guiana': 'Cayenne',
    'French Polynesia': 'Papeete',
    'Gibraltar': 'Gibraltar',
    'Greenland': 'Nuuk',
    'Guam': 'Hagatna',
    'Guernsey': 'St.Peter Port',
    'Jersey': 'Saint Helier',
    'Isle of Man': 'Douglas',
    'Madeira': 'Funchal',
    'Martinique': 'FortdeFrance',
    'Mayotte': 'Mamoudzou',
    'Montserrat': 'Plymouth',
    'Netherlands Antilles': 'Willemstad',
    'New Caledonia': 'Noumea',
    'Niue': 'Alofi',
    'Norfolk Island': 'Kingston',
    'Northern Mariana Islands': 'Saipan',
    'Northern Ireland': 'Belfast',
    'Pitcairn Island': 'Adamstown',
    'Puerto Rico': 'San Juan',
    'Reunion': 'Saint Denis',
    'St.Helena': 'Jamestown',
    'Saint Pierre and Miquelon': 'Saint Pierre',
    'Abkhazia': 'Sukhumi',
    'Basque Country': 'Vitoria Gasteiz',
    'Chechnya': 'Grozny',
    'Iraqi Kurdistan': 'Arbil',
    'Kosovo': 'Pristina',
    'Nagorno Karabakh': 'Stepanakert',
    'Palestine': 'Jerusalem',
    'Puntland': 'Garoowe',
    'Somaliland': 'Hargeisa',
    'South Ossetia': 'Tskhinvali',
    'Transnistria': 'Tiraspol',
    'Tamil Eelam': 'Kilinochchi',
    'South Sudan': 'Juba'
}

def getcountry(s):
    for k, v in capitals.items():
        if (v == s):
            return k
    # Not found, return s
    return s
